export enum BytiumDependencyTypeEnum {
  PROVIDER = "PROVIDER",
  CONTROLLER = "CONTROLLER",
  CUSTOM_PROVIDER = "CUSTOM_PROVIDER",
  MULTI_PROVIDER = "MULTI_PROVIDER",
  EXTERNAL_PROVIDER = "EXTERNAL_PROVIDER",
  MODULE = "MODULE",
  EXTERNAL_MODULE = "EXTERNAL_MODULE",
  RESOURCE = "RESOURCE",
  EXTERNAL_RESOURCE = "EXTERNAL_RESOURCE",
}
